Fixed JIRA issue UNI-107: Make sure the JpaModule is not loaded when the spring-orm dependency is missing, instead of having your tests fail on an uncaught NoClassDefFoundError.